version: "3.9"
services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: sodium
      POSTGRES_PASSWORD: sodium
      POSTGRES_DB: sodium
    ports: ["5432:5432"]
    healthcheck: { test: ["CMD-SHELL", "pg_isready -U sodium"], interval: 5s, timeout: 5s, retries: 10 }
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio:RELEASE.2025-01-11T06-03-02Z
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: devaccess
      MINIO_ROOT_PASSWORD: devsecret
    ports: ["9000:9000", "9090:9090"]
  mailpit:
    image: axllent/mailpit:latest
    ports: ["1025:1025", "8025:8025"]
  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports: ["7700:7700"]
